const express = require('express')
const apiRoutes = require('./routes')
const categoryRoutes = require('./routes/categories')
const transactionRoutes = require('./routes/transactions')
const budgetRoutes = require('./routes/budgets')
const dashboardRoutes = require('./routes/dashboard')
const reportRoutes = require('./routes/reports')
const accountRoutes = require('./routes/accounts')
const recurringTransactionRoutes = require('./routes/recurringTransactions')
const recurringBudgetRoutes = require('./routes/recurringBudgets')
const goalRoutes = require('./routes/goals')
const analyticsRoutes = require('./routes/analytics')
const exportRoutes = require('./routes/export')
const notificationRoutes = require('./routes/notifications')
const { notFound } = require('./middleware/notFound')
const { errorHandler } = require('./middleware/errorHandler')

const app = express()

app.use(express.json())

app.use('/api', apiRoutes)
app.use('/api/categories', categoryRoutes)
app.use('/api/transactions', transactionRoutes)
app.use('/api/budgets', budgetRoutes)
app.use('/api/dashboard', dashboardRoutes)
app.use('/api/reports', reportRoutes)
app.use('/api/accounts', accountRoutes)
app.use('/api/recurring-transactions', recurringTransactionRoutes)
app.use('/api/recurring-budgets', recurringBudgetRoutes)
app.use('/api/goals', goalRoutes)
app.use('/api/analytics', analyticsRoutes)
app.use('/api/export', exportRoutes)
app.use('/api/notifications', notificationRoutes)

app.use(notFound)
app.use(errorHandler)

module.exports = app