const express = require('express')
const apiRoutes = require('./routes')
const authRoutes = require('./routes/auth')
const categoryRoutes = require('./routes/categories')
const transactionRoutes = require('./routes/transactions')
const budgetRoutes = require('./routes/budgets')
const dashboardRoutes = require('./routes/dashboard')
const reportRoutes = require('./routes/reports')
const accountRoutes = require('./routes/accounts')
const recurringTransactionRoutes = require('./routes/recurringTransactions')
const recurringBudgetRoutes = require('./routes/recurringBudgets')
const goalRoutes = require('./routes/goals')
const analyticsRoutes = require('./routes/analytics')
const aiInsightsRoutes = require('./routes/aiInsights')
const exportRoutes = require('./routes/export')
const notificationRoutes = require('./routes/notifications')
const { requireAuth } = require('./middleware/requireAuth')
const { notFound } = require('./middleware/notFound')
const { errorHandler } = require('./middleware/errorHandler')

const app = express()

app.use(express.json())

app.use('/api', apiRoutes)
app.use('/api/auth', authRoutes)
app.use('/api/categories', requireAuth, categoryRoutes)
app.use('/api/transactions', requireAuth, transactionRoutes)
app.use('/api/budgets', requireAuth, budgetRoutes)
app.use('/api/dashboard', requireAuth, dashboardRoutes)
app.use('/api/reports', requireAuth, reportRoutes)
app.use('/api/accounts', requireAuth, accountRoutes)
app.use('/api/recurring-transactions', requireAuth, recurringTransactionRoutes)
app.use('/api/recurring-budgets', requireAuth, recurringBudgetRoutes)
app.use('/api/goals', requireAuth, goalRoutes)
app.use('/api/analytics', requireAuth, analyticsRoutes)
app.use('/api/ai-insights', requireAuth, aiInsightsRoutes)
app.use('/api/export', requireAuth, exportRoutes)
app.use('/api/notifications', requireAuth, notificationRoutes)

app.use(notFound)
app.use(errorHandler)

module.exports = app